### ISSUE TITLE
sleep

### ISSUE THREAD

**Issue by batitskiy** [allyssonmoscoso/ThinkPadL470-OpenCoreEFI#1]
Good day!
How do the volume, backlight buttons (F1 ... F12) behave after sleep? 
They don't work for me.

**Comment by allyssonmoscoso** [comment]
Try with this, open terminal and run:

```sudo pmset -b hibernatemode 25```

```sudo pmset -c hibernatemode 0```

Reboot, sleep and wake.

**Comment by batitskiy** [comment]
Thank you. Works if the PC itself falls asleep.
If you send it manually to sleep, F1 .. disappears.
